# Generated by Django 5.0.2 on 2024-08-08 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0002_resume_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="image",
        ),
    ]
